// Declarative pipeline

pipeline { 
    agent {  //Master node will connect to the below agent and run the jobs
        node {
            label 'Agent' //Lable name of the agent
        }
    }

    stages { // This is called build
        stage('Build') {    
            steps {
                echo 'Building..'  // echo is a shell command to print
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {  // This is post i.e it tells what to excute after build
        always { 
            echo 'This triggers after the build'
        }
        success { 
            echo 'This will run if the build is sucess'
        }
    }
}